import { createFileRoute, useServerFn } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { CheckCircle2 } from "lucide-react";
import { submitApp } from "@/lib/apps.functions";
import { categories } from "@/lib/categories";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
export const Route=createFileRoute("/submit")({head:()=>({meta:[{title:"Submit an app — APPLIFYR"},{name:"description",content:"Submit your software for review and inclusion in the APPLIFYR directory."},{property:"og:title",content:"Submit an app — APPLIFYR"},{property:"og:description",content:"Submit your software for review and inclusion in the APPLIFYR directory."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:SubmitPage});
function SubmitPage(){const submit=useServerFn(submitApp);const[done,setDone]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await submit({data:{name:String(f.get('name')),websiteUrl:String(f.get('websiteUrl')),category:String(f.get('category')) as 'productivity',tagline:String(f.get('tagline'))}});setDone(true)}catch(err){setError(err instanceof Error?err.message:'Submission failed')}finally{setBusy(false)}}if(done)return <section className="grid min-h-[70vh] place-items-center px-5"><div className="max-w-md text-center"><CheckCircle2 className="mx-auto size-10 text-signal"/><h1 className="mt-6 font-display text-4xl font-semibold">Signal received.</h1><p className="mt-3 text-muted-foreground">Your app is in the review queue. We’ll verify it before it enters the public index.</p></div></section>;return <section className="mx-auto grid max-w-5xl gap-12 px-5 py-16 md:grid-cols-[1fr_1.2fr] lg:px-8"><div><p className="font-mono text-xs uppercase text-signal">Submission / Intake</p><h1 className="mt-4 font-display text-5xl font-semibold">Put your app on the radar.</h1><p className="mt-5 leading-7 text-muted-foreground">Tell us what you built. Every submission is reviewed before appearing in the directory.</p></div><form onSubmit={onSubmit} className="space-y-6 border border-border bg-card p-7"><div className="space-y-2"><Label htmlFor="name">App name</Label><Input id="name" name="name" required minLength={2}/></div><div className="space-y-2"><Label htmlFor="websiteUrl">Website</Label><Input id="websiteUrl" name="websiteUrl" type="url" placeholder="https://" required/></div><div className="space-y-2"><Label htmlFor="category">Category</Label><select id="category" name="category" required className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm">{categories.map(c=><option key={c.slug} value={c.slug}>{c.label}</option>)}</select></div><div className="space-y-2"><Label htmlFor="tagline">One-line pitch</Label><Textarea id="tagline" name="tagline" required minLength={8} maxLength={140}/></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button className="w-full" type="submit" disabled={busy}>{busy?'Submitting…':'Submit for review'}</Button></form></section>}
