/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForBuildersRouteImport } from './routes/for-builders'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AppSlugRouteImport } from './routes/app/$slug'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as ApiPublicIngestAppRouteImport } from './routes/api/public/ingest-app'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBuildersRoute = ForBuildersRouteImport.update({
  id: '/for-builders',
  path: '/for-builders',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSlugRoute = AppSlugRouteImport.update({
  id: '/app/$slug',
  path: '/app/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestAppRoute = ApiPublicIngestAppRouteImport.update({
  id: '/api/public/ingest-app',
  path: '/api/public/ingest-app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/explore': typeof ExploreRoute
  '/for-builders': typeof ForBuildersRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/app/$slug': typeof AppSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/api/public/ingest-app': typeof ApiPublicIngestAppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/explore': typeof ExploreRoute
  '/for-builders': typeof ForBuildersRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/app/$slug': typeof AppSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/api/public/ingest-app': typeof ApiPublicIngestAppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/explore': typeof ExploreRoute
  '/for-builders': typeof ForBuildersRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/app/$slug': typeof AppSlugRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/api/public/ingest-app': typeof ApiPublicIngestAppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/explore'
    | '/for-builders'
    | '/sign-in'
    | '/sitemap.xml'
    | '/submit'
    | '/app/$slug'
    | '/category/$category'
    | '/api/public/ingest-app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/explore'
    | '/for-builders'
    | '/sign-in'
    | '/sitemap.xml'
    | '/submit'
    | '/app/$slug'
    | '/category/$category'
    | '/api/public/ingest-app'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/explore'
    | '/for-builders'
    | '/sign-in'
    | '/sitemap.xml'
    | '/submit'
    | '/app/$slug'
    | '/category/$category'
    | '/api/public/ingest-app'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  ExploreRoute: typeof ExploreRoute
  ForBuildersRoute: typeof ForBuildersRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  AppSlugRoute: typeof AppSlugRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ApiPublicIngestAppRoute: typeof ApiPublicIngestAppRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-builders': {
      id: '/for-builders'
      path: '/for-builders'
      fullPath: '/for-builders'
      preLoaderRoute: typeof ForBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$slug': {
      id: '/app/$slug'
      path: '/app/$slug'
      fullPath: '/app/$slug'
      preLoaderRoute: typeof AppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-app': {
      id: '/api/public/ingest-app'
      path: '/api/public/ingest-app'
      fullPath: '/api/public/ingest-app'
      preLoaderRoute: typeof ApiPublicIngestAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  ExploreRoute: ExploreRoute,
  ForBuildersRoute: ForBuildersRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  AppSlugRoute: AppSlugRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ApiPublicIngestAppRoute: ApiPublicIngestAppRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
